### ISSUE TITLE
采集列表有问题

### ISSUE THREAD

**Issue by mynameNB** [hehepi/94so#3]
![QQ图片20211101163907](https://user-images.githubusercontent.com/93515597/139644875-4b9b012c-7530-4263-901c-4803413c72af.png)
![QQ图片20211101163902](https://user-images.githubusercontent.com/93515597/139644878-335591db-8778-4697-a591-a0b7a60b23ad.png)

**Comment by hehepi** [comment]
好的，下一版 修正对“支持” 二字得支持

**Comment by hehepi** [comment]
如还有其他 文字 问题 请继续反馈

**Comment by mynameNB** [comment]
有很多字过滤了

**Comment by hehepi** [comment]
目前方式就是 只保留主要标题 其他说明啥得会全部删除

**Comment by mynameNB** [comment]
最好不要去除吧

**Comment by hehepi** [comment]
去掉是比较好的，因为有些标题特别得长

**Comment by mynameNB** [comment]
![QQ图片20211101165527](https://user-images.githubusercontent.com/93515597/139646873-4dc49cbf-4888-459d-b5b8-1bb9fe961322.png)
![QQ图片20211101165544](https://user-images.githubusercontent.com/93515597/139646903-5a03fb8b-3225-4d72-a945-f28b0f6fcaa7.png)

**Comment by mynameNB** [comment]
可以自己过滤去除 机器去除特别怪

**Comment by hehepi** [comment]
好的

**Comment by mynameNB** [comment]
还有内容的&nbsp;&nbsp;&nbsp;&nbsp;都被过滤了

**Comment by mynameNB** [comment]
&nbsp;

**Comment by mynameNB** [comment]
nbsp;

**Comment by mynameNB** [comment]
导致开头没有空格

**Comment by hehepi** [comment]
好的，后面版本修正
